---
# tasks file for py-openstack-dev

- name: Install ceilo dependencies
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - libmysqlclient-dev
    - npm
    - libffi-dev
    - libsqlite3-dev
    - libxml2
    - libxml2-dev
    - libxslt-dev
    - libzmq-dev # oslo tests with zmq driver for rpc
    - tidy # libtidy for ceilometer docs
    - libpq-dev # postgresql dev tools
    - pkg-config # libvirt-python package build
    - python-pymongo
    - mongodb-server
    - mongodb
    - libnspr4-dev
    - libldap2-dev # python-ldap
    - libsasl2-dev # python-ldap
    - libssl-dev # python-ldap
    - gettext

- name: Clone ceilometer repo
  git: repo=https://github.com/openstack/ceilometer
          dest={{ source_path }}/ceilometer

- name: Run ceilometer requirements
  pip: requirements={{ source_path }}/ceilometer/requirements.txt
          virtualenv={{ py_venv_path }}
